# Operasi Aritmatika
numpy --> elementwise

In [2]:
import numpy as np

# list python
a = [1,2,3,4,5]
b = [6,7,8,9,10]

# array NumPy
a_np = np.array([1,2,3,4,5])
b_np = np.array([6,7,8,9,10])

## Penjumlahan

In [7]:
hasil_1 = a + b
hasil_2 = a_np + b_np
print(f"penjumlahan arr biasa: {hasil_1}")
print(f"penjumlahan arr numpy: {hasil_2}")

penjumlahan arr biasa: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
penjumlahan arr numpy: [ 7  9 11 13 15]


## Pengurangan

In [8]:
# hasil_1 = a - b  # akan error
hasil_2 = a_np - b_np
# print(f"pengurangan arr biasa: {hasil_1}")
print(f"pengurangan arr numpy: {hasil_2}")

pengurangan arr numpy: [-5 -5 -5 -5 -5]


## Operasi Lainnya

In [11]:
hasil_1 = a_np * b_np
hasil_2 = a_np / b_np
hasil_3 = a_np ** b_np
print(f"perkalian arr numpy: {hasil_1}")
print(f"perkalian arr numpy: {hasil_2}")
print(f"pengurangan arr numpy: {hasil_3}")

perkalian arr numpy: [ 6 14 24 36 50]
perkalian arr numpy: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
pengurangan arr numpy: [      1     128    6561  262144 9765625]


## Multidimensi Array (Matriks)

In [14]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

d = np.array([[9, 6, 7],
              [3, 10, 2],
              [8, 4, 1]])

print(c+d)
print()
print(c*d)


[[10  8 10]
 [ 7 15  8]
 [15 12 10]]

[[ 9 12 21]
 [12 50 12]
 [56 32  9]]


In [16]:
def kuadrat(row, height):
    return height**2

b = np.fromfunction(kuadrat, (1, 10), dtype=int)
print(b)
print()

def tambah(kolom, baris):
    return kolom + baris

c = np.fromfunction(tambah, (2, 3), dtype=int)
print(c)

[[ 0  1  4  9 16 25 36 49 64 81]]

[[0 1 2]
 [1 2 3]]
