# Python standart list

In [2]:
# Kita dapat membuat list integer sebagai berikut:
list_int = list(range(10)) # list angka dari 0 s.s. 9
print(list_int, " type datanya item-1: ", type(list_int[0]))

# kita juga dapat membuat list string
list_str = [str(n) for n in list_int]
print(list_str, " type data item-1: ", type(list_str[0]))

# karena python itu "dynamicly typed" maka kita dapat membuat list dengan tipe data heterogen
list_hetero = [True, 1, 1.23, 'hello']
print(f"""{list_hetero}, 
tipe data item-1: {type(list_hetero[0])},
tipe data item-2: {type(list_hetero[1])},
tipe data item-3: {type(list_hetero[2])},
tipe data item-4: {type(list_hetero[3])},""")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  type datanya item-1:  <class 'int'>
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']  type data item-1:  <class 'str'>
[True, 1, 1.23, 'hello'], 
tipe data item-1: <class 'bool'>,
tipe data item-2: <class 'int'>,
tipe data item-3: <class 'float'>,
tipe data item-4: <class 'str'>,


## Fixed-type Array di Python

In [3]:
# dengan melakukan import array
import array
list_dynamic = list(range(10))
list_fixed = array.array('i', list(range(10)))
print(list_dynamic)
print(list_fixed, " ", type(list_fixed))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   <class 'array.array'>


# NumPy

In [4]:
# Import numpy dengan singkatan np
import numpy as np

## Membuat array dengan numpy dari list-python

In [5]:
np_array = np.array([x**2 for x in range(10)])
np_array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Tidak seperti list standar python, numpy membatasi item array pada tipe yang sejenis. Jika tidak, maka numpy akan melakukan casting data jika dimungkinkan.

In [6]:
# contoh, mengisi array dengan float dan integer
np_array = np.array([1, 2, 3.3, 4.0, 2])
np_array # all casted to the same type, float

array([1. , 2. , 3.3, 4. , 2. ])

Jika kita ingin mengatur tipe data secara eksplisit, gunakan keyword ```dtype```

In [7]:
# contoh, mengatur data float ke dalam bentuk int
np_array = np.array([1.1, 2.5, 3.2, 4.7, 5.5], dtype="int8")
np_array

array([1, 2, 3, 4, 5], dtype=int8)

## Membuat array from scratch

Untuk array yang lebih besar, akan lebih efisien jika menggaunakan apa yang disediakan numpy (built in)

In [8]:
# membuat array 1D yang isinya angka nol
arrayNol1D = np.zeros(10, dtype="int8")
arrayNol1D

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
# membuat array 2d yang isinya nol  
arrayNol2D = np.zeros((4,4), dtype="int8")
arrayNol2D

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [10]:
# membuat array yang itemnya floating-point bernilai 1, dengan dimensi 3x5
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# membuat array yang tersisi angka tertentu full
np.full((3,5), 9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [12]:
# membuat array yang dimulai dari 0, loncat 2, sampai dengan 20
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# membuat array dengan 10 item yang berjakan sama dari 0 s.d. 2
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [14]:
# membuat array 3x4 yang terdistribusi uniform, nilainya random antara 0 s.d. 1
np.random.random((3,4))

array([[0.35943481, 0.08862132, 0.83015575, 0.60999367],
       [0.79681088, 0.6282732 , 0.4114517 , 0.6156312 ],
       [0.23466842, 0.09638117, 0.92033632, 0.52574216]])

In [15]:
# membuat array 3x3 yang terdistribusi normal, meannya 0, std. deviasinya 1
np.random.normal(0,1,(3,3))

array([[-1.05216266, -0.83945206,  1.44848643],
       [-1.87556437,  1.03833374,  0.8749918 ],
       [ 0.40220692, -0.65539082,  1.27105572]])

In [16]:
# membuat array 3x3 dengan item random dalam interval 0-10
np.random.randint(0,10,(3,3))

array([[8, 8, 7],
       [2, 9, 0],
       [9, 8, 8]])

In [17]:
# membuat 3x3 matrix identitas
np.eye(3)
# np.identity(3) # the same

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# membuat array tiga integer tanpa inisiasi
# nilainya adalah apapun yang ada di lokasi memori itu
np.empty(3)

array([1., 1., 1.])

## Dasar-dasar array numpy

### Array attributes

Kita akan mulai dengan membuat tiga array random, gunakan ```seed``` untuk memastikan nilai random pada ketiga array adalah sama (pseudo-random).

In [19]:
np.random.seed(1)
a123 = [np.random.randint(size=6, high=10, low=0), # array 1D
        np.random.randint(size=(3,4), high=10, low=0), # array 2D
        np.random.randint(size=(3,4,5), high=10, low=0)]# array 3D

# print it out
j = 1
for i in a123:
    print(f" a{j} ".center(20,"="), f"""
ndim\t : {i.ndim}
shape\t : {i.shape}
size\t : {i.size}
dtype\t : {i.dtype}
itemsize : {i.itemsize}
nbytes\t : {i.nbytes}

""")
    j+=1

======== a1 ======== 
ndim	 : 1
shape	 : (6,)
size	 : 6
dtype	 : int64
itemsize : 8
nbytes	 : 48


======== a2 ======== 
ndim	 : 2
shape	 : (3, 4)
size	 : 12
dtype	 : int64
itemsize : 8
nbytes	 : 96


======== a3 ======== 
ndim	 : 3
shape	 : (3, 4, 5)
size	 : 60
dtype	 : int64
itemsize : 8
nbytes	 : 480




### Indexing array

In [20]:
# ambil elemen array
a1 = np.arange(10)
print(a1)
print(a1[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [21]:
# ambil elemen array dari akhir
print(a1[-2])

8


In [22]:
np.random.seed(1)
a2 = np.random.randint(0,20,(5,5))
print(a2,end="\n\n")
print(a2[2,2])

[[ 5 11 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 13  6]
 [18  5 18 11 10]
 [14 18  4  9 17]]

7


### Slicing Array

In [33]:
x = np.arange(10)
print(x)
print(x[0])
print(x[0:9])
print(x[0:9:2])
print(x[::2])
print(x[4::2])
print(x[7:])
print(x[:3])
print(x[::-1])
print(x[-1:4:-1])
print(x[-1:6:-1])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[0 2 4 6 8]
[4 6 8]
[7 8 9]
[0 1 2]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5]
[9 8 7]


### Subarray Multidimensional

In [46]:
np.random.seed(1)
k = np.random.randint(0,10,(3,7))
k

array([[5, 8, 9, 5, 0, 0, 1],
       [7, 6, 9, 2, 4, 5, 2],
       [4, 2, 4, 7, 7, 9, 1]])

In [47]:
# ambil dua baris pertama dan 3 kolom pertama saja
k[0:2, 0:3]

array([[5, 8, 9],
       [7, 6, 9]])

In [49]:
# Semua baris, ambil kolom loncat 1
k[:,::2]

array([[5, 9, 0, 1],
       [7, 9, 4, 2],
       [4, 4, 7, 1]])

In [50]:
# reverse juga dapat diterapkan disini
k[::-1,::-1]

array([[1, 9, 7, 7, 4, 2, 4],
       [2, 5, 4, 2, 9, 6, 7],
       [1, 0, 0, 5, 9, 8, 5]])

**Akses kolom atau baris array**

In [53]:
# akses baris pertama
# k[0,:] # atau lebih efisien jika menggunakan
k[0]

array([5, 8, 9, 5, 0, 0, 1])

In [56]:
# akses baris ke-2
k[1]

array([7, 6, 9, 2, 4, 5, 2])

In [59]:
# akses kolom ke 3
k[:,2]

array([9, 9, 4])

### Reshaping Array

In [64]:
# dengan method .reshape()
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
# another way
np.random.seed(1)
x = np.random.randint(0,20, (4,6))
print(x)
x[0].reshape(6,1)

[[ 5 11 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 13  6 18  5 18]
 [11 10 14 18  4  9]]


array([[ 5],
       [11],
       [12],
       [ 8],
       [ 9],
       [11]])

In [79]:
x2 = np.arange(9)
x2[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [81]:
x2[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### Konkatenasi Array dan Splitting