# Komputasi di Array Numpy

## Universal Function

In [28]:
# first let import numpy as np
import numpy as np

### Menjelajahi NumPy's UFuncs

#### Operasi aritmatika

In [29]:
# Tidak perlu looping seperti pada list regular
x = np.arange(-5, 5, 1)
print(f"x\t = {x}")
print(f"x+2\t = {x+2}")
print(f"x+3\t = {x+3}")
print(f"x**2\t = {x**2}")

x	 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x+2	 = [-3 -2 -1  0  1  2  3  4  5  6]
x+3	 = [-2 -1  0  1  2  3  4  5  6  7]
x**2	 = [25 16  9  4  1  0  1  4  9 16]


***atau dengan fungsi***

In [30]:
print(np.power(x,2))
print(np.add(x, 3))

[25 16  9  4  1  0  1  4  9 16]
[-2 -1  0  1  2  3  4  5  6  7]


#### Absolute value

In [31]:
print(np.absolute(x)) 

[5 4 3 2 1 0 1 2 3 4]


In [32]:
# atau secara singkat
print(np.abs(x))

[5 4 3 2 1 0 1 2 3 4]


In [33]:
# universal function: np.absolute() juga dapat menghandle data kompleks dan mengembalikan besarnya
x = np.array([3-4j, 6+8j, 12-16j, 0+1j])
print(np.abs(x))

[ 5. 10. 20.  1.]


#### Fungsi Trigonometri

In [34]:
theta = np.linspace(0, np.pi/2, 4)
print(f"theta \t\t : {theta}")
print(f"sin(theta)\t : {np.sin(theta)}")
print(f"cos(theta)\t : {np.cos(theta)}")
print(f"tan(theta)\t : {np.tan(theta)}")

theta 		 : [0.         0.52359878 1.04719755 1.57079633]
sin(theta)	 : [0.        0.5       0.8660254 1.       ]
cos(theta)	 : [1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
tan(theta)	 : [0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]


In [35]:
# fungsi trigonometri invers juga ada
print(f"sin(theta)\t : {np.sin(theta)}")
print(f"cos(theta)\t : {np.cos(theta)}")
print(f"tan(theta)\t : {np.tan(theta)}")

sin(theta)	 : [0.        0.5       0.8660254 1.       ]
cos(theta)	 : [1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
tan(theta)	 : [0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]


#### Exponen dan logaritma

In [36]:
# Exponen
x = np.array([1, 2, 3])
print(f"x\t: {x}")
print(f"e^x\t: {np.exp(x)}")
print(f"2^x\t: {np.exp2( x )}")
print("".center(20,"="))
print(f"3^x\t=1 {np.power(3, x)}")
print(f"3^x\t=2 {3**x}")
print(f"3^x\t=3 {np.power(x, 3)}")
print(f"3^x\t=4 {x**3}")

x	: [1 2 3]
e^x	: [ 2.71828183  7.3890561  20.08553692]
2^x	: [2. 4. 8.]
3^x	=1 [ 3  9 27]
3^x	=2 [ 3  9 27]
3^x	=3 [ 1  8 27]
3^x	=4 [ 1  8 27]


In [37]:
# Logaritma
# log = ln, log2 = basis 2, log10 = basis 10
x = np.array([1, 2, 4, 10])
print(f"x\t : {x}")
print(f"ln(x)\t : {np.log(x)}")
print(f"2log(x)\t : {np.log2(x)}")
print(f"log(x)\t : {np.log10(x)}")

x	 : [ 1  2  4 10]
ln(x)	 : [0.         0.69314718 1.38629436 2.30258509]
2log(x)	 : [0.         1.         2.         3.32192809]
log(x)	 : [0.         0.30103    0.60205999 1.        ]


terdapat versi khusus yang berguna untuk mengelola presisi yang dihasilkan oleh input yang sangat kecil

In [38]:
x = np.array([0, 0.001, 0.01, 0.1])
print(f"exp(x) - 1 = {np.expm1(x)}")
print(f"log(1 + x) = {np.log1p(x)}")

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### Ufunct spesial

In [39]:
from scipy import special

In [40]:
# Funsi gama (faktorial umum) dan fungsi lain yang berkatian
x = np.array([1, 5, 10])
print(f"gamma(x)     = {special.gamma(x)}")
print(f"ln|gamma(x)  = {special.gammaln(x)}")
print(f"beta(x, 2)   = {special.beta(x, 2)}")

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)  = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [41]:
# Funsi error (Integral dari gaussian)
# compement dan inversnya
x = np.array([0, 0.3, 0.7, 1.0])
print(f"erf(x)   = {special.erf(x)}")
print(f"erfc(x)   = {special.erfc(x)}")
print(f"erfinv(x)   = {special.erfinv(x)}")

erf(x)   = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)   = [0.         0.27246271 0.73286908        inf]


### Fitur lanjutan dari UFunct

#### Menentukan letak output
Alih-alih anda membuat array temporer, kamu dapat menggunkan ini untuk menulis hasil perhitungan ke lokasi memori yang anda inginkan

In [46]:
np.random.seed(1)
x = np.random.randint(0, 9, (3,5))
z = np.empty((3,5))
np.multiply(x, 10, out=z)
print(x)
print(z)

[[5 8 5 0 0]
 [1 7 6 2 4]
 [5 2 4 2 4]]
[[50. 80. 50.  0.  0.]
 [10. 70. 60. 20. 40.]
 [50. 20. 40. 20. 40.]]


In [51]:
i = np.arange(1,6)
j = np.zeros(10)
np.power(i, 2, out=j[::2])
print(j)

[ 1.  0.  4.  0.  9.  0. 16.  0. 25.  0.]


#### Agregat

In [55]:
x = np.arange(1, 5)
np.add.reduce(x)

10

In [56]:
np.arange(1, 5)
np.multiply.reduce(x)

24

In [58]:
np.add.accumulate(x)
np.multiply.accumulate(x)

array([ 1,  2,  6, 24])

#### Outer products

In [63]:
x = np.arange(1, 10)
y = np.multiply.outer(x, x)
print(y)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
