# Komputasi di Array: Broadcasting

## Pengenalan Broadcasting
Broadcasting adalah sekumpulan kumpulan aturan dalam menggunakan fungsi universal pada array yang size-nya berbeda

Pada array dengan size yang sama, operasi dilakukan elemen by elemen

In [18]:
import numpy as np
a = np.array([2, 4, 6])
b = np.array([3, 5, 7])
print(a+b)

[ 5  9 13]


Adanya broadcasting memungkinkan operasi semacam diatas dilakukan pada array yang berbeda sizenya. Misal, kita ingin mengalikan sebuah skalar (yang dapat dianggap array 0-D) dengan array.

In [19]:
print(a * 5)

[10 20 30]


Secara identik, kita dapat melakukan hal yang sama pada array dengan dimensi yang lebih tinggi

In [20]:
c = np.ones((3, 3))
print(f"""a\t = {a}
c\t = 
{c}

a + c\t = 
{a+c}""")

a	 = [2 4 6]
c	 = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

a + c	 = 
[[3. 5. 7.]
 [3. 5. 7.]
 [3. 5. 7.]]


Kasus diatas relatif lebih mudah dimengerti. Kasus yang lerbih _complicated_ dapat melibatkan broadcasting pada kedua array. Contoh

In [21]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [22]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [23]:
# contoh lagi
a = np.array([1, 2, 3])
b = np.ones((3,3))
print(a)
print(b)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(a+b)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


- **Aturan 1**: Jika dua array berbeda dalam jumlah dimensinya, bentuk dari
salahsatu array dengan dimensi lebih sedikit diisi dengan salah satu dari bagian depannya untuk memenuhi yang lebih besar.
- **Aturan 2**: Jika bentuk kedua array tidak cocok dalam dimensi apa pun, array
dengan bentuk sama dengan 1 dalam dimensi itu direntangkan agar sesuai dengan bentuk lainnya.
- **Aturan 3**: Jika dalam dimensi apa pun ukurannya tidak sama dan tidak ada yang sama dengan 1.

Supaya lebih jelas, kita beri contoh satu-persatu

### Broadcasting aturan 1
Mari jumlahkan array 2D ke array 1D

In [25]:
a = np.ones((2, 3))
b = np.arange(3)
print(a)
print(b)
print("\n", a+b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]

 [[1. 2. 3.]
 [1. 2. 3.]]
