# Python standart list

In [6]:
# Kita dapat membuat list integer sebagai berikut:
list_int = list(range(10)) # list angka dari 0 s.s. 9
print(list_int, " type datanya item-1: ", type(list_int[0]))

# kita juga dapat membuat list string
list_str = [str(n) for n in list_int]
print(list_str, " type data item-1: ", type(list_str[0]))

# karena python itu "dynamicly typed" maka kita dapat membuat list dengan tipe data heterogen
list_hetero = [True, 1, 1.23, 'hello']
print(f"""{list_hetero}, 
tipe data item-1: {type(list_hetero[0])},
tipe data item-2: {type(list_hetero[1])},
tipe data item-3: {type(list_hetero[2])},
tipe data item-4: {type(list_hetero[3])},""")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  type datanya item-1:  <class 'int'>
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']  type data item-1:  <class 'str'>
[True, 1, 1.23, 'hello'], 
tiped data item-1: <class 'bool'>,
tiped data item-2: <class 'int'>,
tiped data item-3: <class 'float'>,
tiped data item-4: <class 'str'>,


## Fixed-type Array di Python

In [12]:
# dengan melakukan import array
import array
list_dynamic = list(range(10))
list_fixed = array.array('i', list(range(10)))
print(list_dynamic)
print(list_fixed, " ", type(list_fixed))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   <class 'array.array'>


# NumPy

In [14]:
# Import numpy dengan singkatan np
import numpy as np

## Membuat array dengan numpy dari list-python

In [20]:
np_array = np.array([x**2 for x in range(10)])
np_array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Tidak seperti list standar python, numpy membatasi item array pada tipe yang sejenis. Jika tidak, maka numpy akan melakukan casting data jika dimungkinkan.

In [23]:
# contoh, mengisi array dengan float dan integer
np_array = np.array([1, 2, 3.3, 4.0, 2])
np_array # all casted to the same type, float

array([1. , 2. , 3.3, 4. , 2. ])

Jika kita ingin mengatur tipe data secara eksplisit, gunakan keyword ```dtype```

In [27]:
# contoh, mengatur data float ke dalam bentuk int
np_array = np.array([1.1, 2.5, 3.2, 4.7, 5.5], dtype="int8")
np_array

array([1, 2, 3, 4, 5], dtype=int8)